hello_world:
  path: /world/hello
  controller: App\Controller\WorldController::hello

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
